trigger:
  - master

jobs:
  - job: Linting
    displayName: Linting
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        (Node 12):
          NODE_VERSION: 12
    steps:
      - template: jobs/linting.yml

  - job: Test_Ubuntu
    displayName: Unit tests on Ubuntu
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        (Node 10):
          NODE_VERSION: 10
        (Node 12 + test results & coverage):
          NODE_VERSION: 12
          REPORT_TEST_RESULTS_AND_COVERAGE: true
        (Node 13):
          NODE_VERSION: 13
    steps:
      - template: jobs/unit-tests.yml

  - job: Test_macOS
    displayName: Unit tests on macOS
    pool:
      vmImage: macos-latest
    strategy:
      matrix:
        (Node 12):
          NODE_VERSION: 12
    steps:
      - template: jobs/unit-tests.yml

  - job: Test_Windows
    displayName: Unit tests on Windows
    pool:
      vmImage: vs2017-latest
    strategy:
      matrix:
        (Node 12):
          NODE_VERSION: 12
    steps:
      - template: jobs/unit-tests.yml
